In [1]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/PLACES__Local_Data_for_Better_Health,_County_Data,_2025_release_20260906.csv")

/tmp/ipykernel_5379/3111128515.py:3: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/content/drive/MyDrive/PLACES__Local_Data_for_Better_Health,_County_Data,_2025_release_20260906.csv")

In [2]:
print(df.shape)

(229298, 22)

In [3]:
print(df.columns.to_list())

['Year', 'StateAbbr', 'StateDesc', 'LocationName', 'DataSource', 'Category', 'Measure', 'Data_Value_Unit', 'Data_Value_Type', 'Data_Value', 'Data_Value_Footnote_Symbol', 'Data_Value_Footnote', 'Low_Confidence_Limit', 'High_Confidence_Limit', 'TotalPopulation', 'TotalPop18plus', 'LocationID', 'CategoryID', 'MeasureId', 'DataValueTypeID', 'Short_Question_Text', 'Geolocation']

In [4]:
df.head(5)

,Year,StateAbbr,StateDesc,LocationName,DataSource,Category,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,...,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,TotalPop18plus,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text,Geolocation
0,2023,AR,Arkansas,Drew,BRFSS,Health Outcomes,Arthritis among adults,%,Crude prevalence,29.9,...,26.6,33.3,"16,945","13,230",5043,HLTHOUT,ARTHRITIS,CrdPrv,Arthritis,POINT (-91.7196579038053 33.5894113647675)
1,2023,AR,Arkansas,Fulton,BRFSS,Health Outcomes,Current asthma among adults,%,Crude prevalence,10.6,...,9.2,11.9,"12,421","9,795",5049,HLTHOUT,CASTHMA,CrdPrv,Current Asthma,POINT (-91.817888079321 36.3816206347765)
2,2023,AR,Arkansas,Howard,BRFSS,Health Outcomes,Arthritis among adults,%,Crude prevalence,31.2,...,27.7,34.8,"12,533","9,311",5061,HLTHOUT,ARTHRITIS,CrdPrv,Arthritis,POINT (-93.9938053308515 34.0889044688856)
3,2023,AR,Arkansas,Miller,BRFSS,Health Outcomes,Stroke among adults,%,Crude prevalence,4.7,...,4.2,5.3,"42,415","32,396",5091,HLTHOUT,STROKE,CrdPrv,Stroke,POINT (-93.8924281761086 33.3123156126392)
4,2023,AR,Arkansas,Ouachita,BRFSS,Disability,Any disability among adults,%,Crude prevalence,42.8,...,37.9,47.8,"21,793","16,948",5103,DISABLT,DISABILITY,CrdPrv,Any Disability,POINT (-92.882040791321 33.593253927504)

In [5]:
df.dtypes

Year                            int64
StateAbbr                      object
StateDesc                      object
LocationName                   object
DataSource                     object
Category                       object
Measure                        object
Data_Value_Unit                object
Data_Value_Type                object
Data_Value                    float64
Data_Value_Footnote_Symbol     object
Data_Value_Footnote            object
Low_Confidence_Limit          float64
High_Confidence_Limit         float64
TotalPopulation                object
TotalPop18plus                 object
LocationID                      int64
CategoryID                     object
MeasureId                      object
DataValueTypeID                object
Short_Question_Text            object
Geolocation                    object
dtype: object

In [6]:
df['Data_Value_Type'].value_counts()

Data_Value_Type
Crude prevalence           114649
Age-adjusted prevalence    114649
Name: count, dtype: int64

In [7]:
df['LocationID'].nunique()

3145

In [8]:
df.describe()

,Year,Data_Value,Low_Confidence_Limit,High_Confidence_Limit,LocationID
count,229298.000000,229232.000000,229232.000000,229232.000000,229298.000000
mean,2022.862842,25.988058,23.056486,29.029283,30051.232353
std,0.344015,22.079617,20.956876,23.147430,15265.440807
min,2022.000000,1.700000,1.500000,1.900000,59.000000
25%,2023.000000,9.800000,8.300000,11.500000,18079.000000
50%,2023.000000,17.600000,14.800000,20.600000,29151.000000
75%,2023.000000,34.400000,29.400000,39.500000,45047.000000
max,2023.000000,93.300000,92.200000,94.200000,56045.000000

In [9]:
disease_count = df['MeasureId'].value_counts().sort_index()
print(disease_count)

MeasureId
ACCESS2         5916
ARTHRITIS       5916
BINGE           5916
BPHIGH          5916
BPMED           5916
CANCER          5916
CASTHMA         5916
CHD             5916
CHECKUP         5916
CHOLSCREEN      5916
COGNITION       5916
COLON_SCREEN    6290
COPD            5916
CSMOKING        5916
DENTAL          6290
DEPRESSION      5916
DIABETES        5916
DISABILITY      5916
EMOTIONSPT      4600
FOODINSECU      4600
FOODSTAMP       4600
GHLTH           5916
HEARING         5916
HIGHCHOL        5916
HOUSINSECU      4600
INDEPLIVE       5916
LACKTRPT        4600
LONELINESS      4600
LPA             5916
MAMMOUSE        6290
MHLTH           5916
MOBILITY        5916
OBESITY         5916
PHLTH           5916
SELFCARE        5916
SHUTUTILITY     4600
SLEEP           6290
STROKE          5916
TEETHLOST       6290
VISION          5916
Name: count, dtype: int64

In [10]:
df[df['MeasureId'] == 'DIABETES']['Data_Value'].describe()

count    5914.000000
mean       12.402858
std         2.844981
min         4.900000
25%        10.300000
50%        12.100000
75%        14.000000
max        27.100000
Name: Data_Value, dtype: float64

In [11]:
df[df['MeasureId'] == 'FOODINSECU']['Data_Value'].describe()

count    4600.000000
mean       16.782261
std         6.044506
min         5.700000
25%        12.500000
50%        15.300000
75%        19.500000
max        46.800000
Name: Data_Value, dtype: float64

In [12]:
# Finding the total missing cells in the entire dataset
missing_cells = df.isnull().sum().sum()
print(f"The missing number of cells are: {missing_cells}")

# Finding the number of missing cells per column
missing_per_column = df.isnull().sum()
print(missing_per_column)

The missing number of cells are: 458794
Year                               0
StateAbbr                          0
StateDesc                          0
LocationName                      80
DataSource                         0
Category                           0
Measure                            0
Data_Value_Unit                    0
Data_Value_Type                    0
Data_Value                        66
Data_Value_Footnote_Symbol    229218
Data_Value_Footnote           229218
Low_Confidence_Limit              66
High_Confidence_Limit             66
TotalPopulation                    0
TotalPop18plus                     0
LocationID                         0
CategoryID                         0
MeasureId                          0
DataValueTypeID                    0
Short_Question_Text                0
Geolocation                       80
dtype: int64

In [13]:
# Ordinal values
df['Data_Value_Type'].value_counts(normalize=True, dropna=False)

Data_Value_Type
Crude prevalence           0.5
Age-adjusted prevalence    0.5
Name: proportion, dtype: float64

In [18]:
# Cleaning the data to only show rows with 'Crude prevalence'
crude_df = df[df['Data_Value_Type'] == 'Crude prevalence']
num_diseases = crude_df['MeasureId'].value_counts().sort_index()
print(num_diseases) # Shows exact number of US counties suffering from each disease/issue

MeasureId
ACCESS2         2958
ARTHRITIS       2958
BINGE           2958
BPHIGH          2958
BPMED           2958
CANCER          2958
CASTHMA         2958
CHD             2958
CHECKUP         2958
CHOLSCREEN      2958
COGNITION       2958
COLON_SCREEN    3145
COPD            2958
CSMOKING        2958
DENTAL          3145
DEPRESSION      2958
DIABETES        2958
DISABILITY      2958
EMOTIONSPT      2300
FOODINSECU      2300
FOODSTAMP       2300
GHLTH           2958
HEARING         2958
HIGHCHOL        2958
HOUSINSECU      2300
INDEPLIVE       2958
LACKTRPT        2300
LONELINESS      2300
LPA             2958
MAMMOUSE        3145
MHLTH           2958
MOBILITY        2958
OBESITY         2958
PHLTH           2958
SELFCARE        2958
SHUTUTILITY     2300
SLEEP           3145
STROKE          2958
TEETHLOST       3145
VISION          2958
Name: count, dtype: int64